name: Rust Release

on:
  push:
    tags:
      - "v*" # 对于匹配 v*的标签（如 v1.0、v2.5.7）的push事件。

jobs:
  build:
    strategy:
      matrix:
        target: [x86_64-unknown-linux-musl] # 定义构建的目标平台
    runs-on: ubuntu-20.04 # 这个作业运行在最新版的Ubuntu上

    steps:
    - name: Checkout source # 获取源码
      uses: actions/checkout@v2

    - name: Install dependencies
      run: sudo sed -i "s#archive.ubuntu.com#mirrors.aliyun.com#g" /etc/apt/sources.list && sudo sed -i "s#security.ubuntu.com#mirrors.aliyun.com#g" /etc/apt/sources.list && sudo apt-get update && sudo apt-get install -y musl-tools

    - name: Setup Rust environment # 设置Rust环境
      uses: actions-rs/toolchain@v1
      with:
        profile: minimal
        toolchain: stable
        target: ${{ matrix.target }} # 设置对应的构建目标
        override: true

    - name: Build # 构建
      run: cargo build --release --target ${{ matrix.target }}

    - name: Zip the Build # 对构建产物进行zip打包
      run: zip -r ${{ secrets.ReleaseZipName }}-${{ matrix.target }} ./target/${{ matrix.target }}/release/ # 改为你的应用名

    - name: Create Release and Upload Release Asset # 创建新的发布版本并上传
      uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/') # 只有在refs中有tags时才执行
      with:
        token: ${{ secrets.RELEASE_GITHUB_TOKEN }} # 使用你刚刚创建的secret
        tag_name: ${{ github.ref }} # 用具有refs/tags的github引用命名tag
        name: Release ${{ github.ref }}
        body: 新的发布版本
        draft: false
        prerelease: false
        files: |
          ${{ secrets.ReleaseZipName }}-${{ matrix.target }}.zip
          LICENSE